name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        extensions: mbstring, intl, pdo, sqlite, bcmath

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Copy env file
      run: cp .env.example .env
    - name: Generate application key
      run: php artisan key:generate
    - name: Setup Jwt Secret
      run: php artisan jwt:secret

    - name: Run tests
      run: vendor/bin/phpunit